name: devcontainer_demo
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel # required for jupyter notebook in VS Code
  - pandas
  - numpy
  - matplotlib
  - ghapi
  - pandas-profiling
